profile_inline = "📁 Profile"
item_categories_inline = "🗄️ Item categories"
faq_inline = "❓ FAQ"
add_change_first_name_inline = "✏️ Add/Change first name"
add_change_last_name_inline = "✏️ Add/Change last name"
add_change_phone_number_inline = "✏️ Add/Change phone number"
share_phone_number_inline = "Share phone number 📱"
